name: AOC
version: '1.0'
license: AllRightsReserved
dependencies:
- containers
- base
- parsec
- hourglass
- vector
- mtl
- array
executables:
  AOC:
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    other-modules:
      AOC1
      AOC2
      AOC3
      AOC4
data-files:
- example.txt
stability: experimental
